<?php

$_fileArray = array(

	array("axe", "2100", "NA", "NA", "Tools", "ToolAxe", "NA"),
	array("bamboo wand", "7590", "NA", "NA", "Tools", "ToolStickBamboo", "NA"),
	array("bug wand", "8769", "NA", "NA", "Tools", "ToolStcikInsect", "NA"),
	array("Bunny Day wand", "12578", "NA", "NA", "Tools", "ToolStickEgg", "NA"),
	array("cherry-blossom wand", "7589", "NA", "NA", "Tools", "ToolStickCherryblossom", "NA"),
	array("colorful fishing rod", "8472", "Yellow", "NA", "Tools", "ToolFishingrodDuck_Remake_0_0", "0_0"),
	array("colorful fishing rod", "8472", "Orange", "NA", "Tools", "ToolFishingrodDuck_Remake_1_0", "1_0"),
	array("colorful fishing rod", "8472", "Light blue", "NA", "Tools", "ToolFishingrodDuck_Remake_2_0", "2_0"),
	array("colorful fishing rod", "8472", "Pink", "NA", "Tools", "ToolFishingrodDuck_Remake_3_0", "3_0"),
	array("colorful fishing rod", "8472", "Green", "NA", "Tools", "ToolFishingrodDuck_Remake_4_0", "4_0"),
	array("colorful fishing rod", "8472", "Purple", "NA", "Tools", "ToolFishingrodDuck_Remake_5_0", "5_0"),
	array("colorful fishing rod", "8472", "White", "NA", "Tools", "ToolFishingrodDuck_Remake_6_0", "6_0"),
	array("colorful fishing rod", "8472", "Gray", "NA", "Tools", "ToolFishingrodDuck_Remake_7_0", "7_0"),
	array("colorful net", "8177", "Yellow & orange", "NA", "Tools", "ToolNetPattern_Remake_0_0", "0_0"),
	array("colorful net", "8177", "Red & yellow", "NA", "Tools", "ToolNetPattern_Remake_1_0", "1_0"),
	array("colorful net", "8177", "Orange & blue", "NA", "Tools", "ToolNetPattern_Remake_2_0", "2_0"),
	array("colorful net", "8177", "Pink & yellow", "NA", "Tools", "ToolNetPattern_Remake_3_0", "3_0"),
	array("colorful net", "8177", "Green & blue", "NA", "Tools", "ToolNetPattern_Remake_4_0", "4_0"),
	array("colorful net", "8177", "Purple & pink", "NA", "Tools", "ToolNetPattern_Remake_5_0", "5_0"),
	array("colorful net", "8177", "White & blue", "NA", "Tools", "ToolNetPattern_Remake_6_0", "6_0"),
	array("colorful net", "8177", "Gray & green", "NA", "Tools", "ToolNetPattern_Remake_7_0", "7_0"),
	array("colorful shovel", "8577", "Yellow", "NA", "Tools", "ToolScoopColorful_Remake_0_0", "0_0"),
	array("colorful shovel", "8577", "Red", "NA", "Tools", "ToolScoopColorful_Remake_1_0", "1_0"),
	array("colorful shovel", "8577", "Blue", "NA", "Tools", "ToolScoopColorful_Remake_2_0", "2_0"),
	array("colorful shovel", "8577", "Pink", "NA", "Tools", "ToolScoopColorful_Remake_3_0", "3_0"),
	array("colorful shovel", "8577", "Green", "NA", "Tools", "ToolScoopColorful_Remake_4_0", "4_0"),
	array("colorful shovel", "8577", "Purple", "NA", "Tools", "ToolScoopColorful_Remake_5_0", "5_0"),
	array("colorful shovel", "8577", "White", "NA", "Tools", "ToolScoopColorful_Remake_6_0", "6_0"),
	array("colorful shovel", "8577", "Black", "NA", "Tools", "ToolScoopColorful_Remake_7_0", "7_0"),
	array("colorful slingshot", "8580", "Yellow", "NA", "Tools", "ToolSlingshotColorful_Remake_0_0", "0_0"),
	array("colorful slingshot", "8580", "Red", "NA", "Tools", "ToolSlingshotColorful_Remake_1_0", "1_0"),
	array("colorful slingshot", "8580", "Blue", "NA", "Tools", "ToolSlingshotColorful_Remake_2_0", "2_0"),
	array("colorful slingshot", "8580", "Pink", "NA", "Tools", "ToolSlingshotColorful_Remake_3_0", "3_0"),
	array("colorful slingshot", "8580", "Green", "NA", "Tools", "ToolSlingshotColorful_Remake_4_0", "4_0"),
	array("colorful slingshot", "8580", "Purple", "NA", "Tools", "ToolSlingshotColorful_Remake_5_0", "5_0"),
	array("colorful slingshot", "8580", "White", "NA", "Tools", "ToolSlingshotColorful_Remake_6_0", "6_0"),
	array("colorful slingshot", "8580", "Black", "NA", "Tools", "ToolSlingshotColorful_Remake_7_0", "7_0"),
	array("colorful watering can", "8534", "Yellow", "NA", "Tools", "ToolWateringColorful_Remake_0_0", "0_0"),
	array("colorful watering can", "8534", "Red", "NA", "Tools", "ToolWateringColorful_Remake_1_0", "1_0"),
	array("colorful watering can", "8534", "Blue", "NA", "Tools", "ToolWateringColorful_Remake_2_0", "2_0"),
	array("colorful watering can", "8534", "Pink", "NA", "Tools", "ToolWateringColorful_Remake_3_0", "3_0"),
	array("colorful watering can", "8534", "Green", "NA", "Tools", "ToolWateringColorful_Remake_4_0", "4_0"),
	array("colorful watering can", "8534", "Purple", "NA", "Tools", "ToolWateringColorful_Remake_5_0", "5_0"),
	array("colorful watering can", "8534", "White", "NA", "Tools", "ToolWateringColorful_Remake_6_0", "6_0"),
	array("colorful watering can", "8534", "Black", "NA", "Tools", "ToolWateringColorful_Remake_7_0", "7_0"),
	array("cosmos wand", "5092", "NA", "NA", "Tools", "ToolStickCosmos", "NA"),
	array("elephant watering can", "8535", "Gray", "NA", "Tools", "ToolWateringElephant_Remake_0_0", "0_0"),
	array("elephant watering can", "8535", "Green", "NA", "Tools", "ToolWateringElephant_Remake_1_0", "1_0"),
	array("elephant watering can", "8535", "Blue", "NA", "Tools", "ToolWateringElephant_Remake_2_0", "2_0"),
	array("elephant watering can", "8535", "Pink", "NA", "Tools", "ToolWateringElephant_Remake_3_0", "3_0"),
	array("elephant watering can", "8535", "Red", "NA", "Tools", "ToolWateringElephant_Remake_4_0", "4_0"),
	array("elephant watering can", "8535", "Yellow", "NA", "Tools", "ToolWateringElephant_Remake_5_0", "5_0"),
	array("elephant watering can", "8535", "Light blue", "NA", "Tools", "ToolWateringElephant_Remake_6_0", "6_0"),
	array("elephant watering can", "8535", "Black", "NA", "Tools", "ToolWateringElephant_Remake_7_0", "7_0"),
	array("fish fishing rod", "8471", "Green", "NA", "Tools", "ToolFishingrodColorful_Remake_0_0", "0_0"),
	array("fish fishing rod", "8471", "Yellow", "NA", "Tools", "ToolFishingrodColorful_Remake_1_0", "1_0"),
	array("fish fishing rod", "8471", "Orange", "NA", "Tools", "ToolFishingrodColorful_Remake_2_0", "2_0"),
	array("fish fishing rod", "8471", "Light blue", "NA", "Tools", "ToolFishingrodColorful_Remake_3_0", "3_0"),
	array("fish fishing rod", "8471", "Blue", "NA", "Tools", "ToolFishingrodColorful_Remake_4_0", "4_0"),
	array("fish fishing rod", "8471", "Purple", "NA", "Tools", "ToolFishingrodColorful_Remake_5_0", "5_0"),
	array("fish fishing rod", "8471", "Pink", "NA", "Tools", "ToolFishingrodColorful_Remake_6_0", "6_0"),
	array("fish fishing rod", "8471", "Red", "NA", "Tools", "ToolFishingrodColorful_Remake_7_0", "7_0"),
	array("fish wand", "8770", "NA", "NA", "Tools", "ToolStickFish", "NA"),
	array("fishing rod", "2377", "Blue", "NA", "Tools", "ToolAngling_Remake_0_0", "0_0"),
	array("fishing rod", "2377", "Yellow", "NA", "Tools", "ToolAngling_Remake_1_0", "1_0"),
	array("fishing rod", "2377", "Green", "NA", "Tools", "ToolAngling_Remake_2_0", "2_0"),
	array("fishing rod", "2377", "Red", "NA", "Tools", "ToolAngling_Remake_3_0", "3_0"),
	array("fishing rod", "2377", "Purple", "NA", "Tools", "ToolAngling_Remake_4_0", "4_0"),
	array("fishing rod", "2377", "Pink", "NA", "Tools", "ToolAngling_Remake_5_0", "5_0"),
	array("fishing rod", "2377", "White", "NA", "Tools", "ToolAngling_Remake_6_0", "6_0"),
	array("fishing rod", "2377", "Black", "NA", "Tools", "ToolAngling_Remake_7_0", "7_0"),
	array("flimsy axe", "3068", "NA", "NA", "Tools", "ToolAxeStone", "NA"),
	array("flimsy fishing rod", "3084", "NA", "NA", "Tools", "ToolFishingrodWood", "NA"),
	array("flimsy net", "2376", "NA", "NA", "Tools", "ToolNet", "NA"),
	array("flimsy shovel", "3082", "NA", "NA", "Tools", "ToolShovelWood", "NA"),
	array("flimsy watering can", "3083", "NA", "NA", "Tools", "ToolWateringWood", "NA"),
	array("golden axe", "9617", "NA", "NA", "Tools", "ToolAxeGold", "NA"),
	array("golden net", "8179", "NA", "NA", "Tools", "ToolNetGold", "NA"),
	array("golden rod", "8660", "NA", "NA", "Tools", "ToolFishingrodGold", "NA"),
	array("golden shovel", "8574", "NA", "NA", "Tools", "ToolScoopGold", "NA"),
	array("golden slingshot", "8578", "NA", "NA", "Tools", "ToolSlingshotGold", "NA"),
	array("golden wand", "7591", "NA", "NA", "Tools", "ToolStickGolden", "NA"),
	array("golden watering can", "8533", "NA", "NA", "Tools", "ToolWateringGold", "NA"),
	array("hyacinth wand", "5083", "NA", "NA", "Tools", "ToolStickHyacinth", "NA"),
	array("ice wand", "7585", "NA", "NA", "Tools", "ToolStickSnow", "NA"),
	array("iron wand", "7592", "NA", "NA", "Tools", "ToolStickIron", "NA"),
	array("ladder", "2615", "NA", "NA", "Tools", "ToolLadder", "NA"),
	array("light stick", "5741", "NA", "NA", "Tools", "ToolSticklight", "NA"),
	array("lily wand", "5094", "NA", "NA", "Tools", "ToolStickYuri", "NA"),
	array("mums wand", "5095", "NA", "NA", "Tools", "ToolStickChrysanthemum", "NA"),
	array("mushroom wand", "7588", "Ordinary mushroom", "NA", "Tools", "ToolStickMushroom_Remake_0_0", "0_0"),
	array("mushroom wand", "7588", "White mushroom", "NA", "Tools", "ToolStickMushroom_Remake_1_0", "1_0"),
	array("mushroom wand", "7588", "Strange mushroom", "NA", "Tools", "ToolStickMushroom_Remake_2_0", "2_0"),
	array("mushroom wand", "7588", "Red mushroom", "NA", "Tools", "ToolStickMushroom_Remake_3_0", "3_0"),
	array("mushroom wand", "7588", "Yellow mushroom", "NA", "Tools", "ToolStickMushroom_Remake_4_0", "4_0"),
	array("net", "5784", "Red", "NA", "Tools", "ToolNetNormal_Remake_0_0", "0_0"),
	array("net", "5784", "Yellow", "NA", "Tools", "ToolNetNormal_Remake_1_0", "1_0"),
	array("net", "5784", "Green", "NA", "Tools", "ToolNetNormal_Remake_2_0", "2_0"),
	array("net", "5784", "Blue", "NA", "Tools", "ToolNetNormal_Remake_3_0", "3_0"),
	array("net", "5784", "Purple", "NA", "Tools", "ToolNetNormal_Remake_4_0", "4_0"),
	array("net", "5784", "Pink", "NA", "Tools", "ToolNetNormal_Remake_5_0", "5_0"),
	array("net", "5784", "White", "NA", "Tools", "ToolNetNormal_Remake_6_0", "6_0"),
	array("net", "5784", "Black", "NA", "Tools", "ToolNetNormal_Remake_7_0", "7_0"),
	array("Nook Inc. uchiwa fan", "9762", "NA", "NA", "Tools", "ToolFanNook0", "NA"),
	array("ocarina", "5320", "NA", "NA", "Tools", "ToolOcarina", "NA"),
	array("outdoorsy fishing rod", "8473", "Avocado", "NA", "Tools", "ToolFishingrodOutdoor_Remake_0_0", "0_0"),
	array("outdoorsy fishing rod", "8473", "Orange", "NA", "Tools", "ToolFishingrodOutdoor_Remake_1_0", "1_0"),
	array("outdoorsy fishing rod", "8473", "Light blue", "NA", "Tools", "ToolFishingrodOutdoor_Remake_2_0", "2_0"),
	array("outdoorsy fishing rod", "8473", "Red", "NA", "Tools", "ToolFishingrodOutdoor_Remake_3_0", "3_0"),
	array("outdoorsy fishing rod", "8473", "Beige", "NA", "Tools", "ToolFishingrodOutdoor_Remake_4_0", "4_0"),
	array("outdoorsy fishing rod", "8473", "Pink", "NA", "Tools", "ToolFishingrodOutdoor_Remake_5_0", "5_0"),
	array("outdoorsy fishing rod", "8473", "Yellow", "NA", "Tools", "ToolFishingrodOutdoor_Remake_6_0", "6_0"),
	array("outdoorsy fishing rod", "8473", "Black", "NA", "Tools", "ToolFishingrodOutdoor_Remake_7_0", "7_0"),
	array("outdoorsy net", "8178", "Avocado", "NA", "Tools", "ToolNetOutdoor_Remake_0_0", "0_0"),
	array("outdoorsy net", "8178", "Orange", "NA", "Tools", "ToolNetOutdoor_Remake_1_0", "1_0"),
	array("outdoorsy net", "8178", "Light blue", "NA", "Tools", "ToolNetOutdoor_Remake_2_0", "2_0"),
	array("outdoorsy net", "8178", "Red", "NA", "Tools", "ToolNetOutdoor_Remake_3_0", "3_0"),
	array("outdoorsy net", "8178", "Beige", "NA", "Tools", "ToolNetOutdoor_Remake_4_0", "4_0"),
	array("outdoorsy net", "8178", "Pink", "NA", "Tools", "ToolNetOutdoor_Remake_5_0", "5_0"),
	array("outdoorsy net", "8178", "Yellow", "NA", "Tools", "ToolNetOutdoor_Remake_6_0", "6_0"),
	array("outdoorsy net", "8178", "Black", "NA", "Tools", "ToolNetOutdoor_Remake_7_0", "7_0"),
	array("outdoorsy shovel", "8575", "Avocado", "NA", "Tools", "ToolScoopOutdoor_Remake_0_0", "0_0"),
	array("outdoorsy shovel", "8575", "Orange", "NA", "Tools", "ToolScoopOutdoor_Remake_1_0", "1_0"),
	array("outdoorsy shovel", "8575", "Light blue", "NA", "Tools", "ToolScoopOutdoor_Remake_2_0", "2_0"),
	array("outdoorsy shovel", "8575", "Red", "NA", "Tools", "ToolScoopOutdoor_Remake_3_0", "3_0"),
	array("outdoorsy shovel", "8575", "Beige", "NA", "Tools", "ToolScoopOutdoor_Remake_4_0", "4_0"),
	array("outdoorsy shovel", "8575", "Pink", "NA", "Tools", "ToolScoopOutdoor_Remake_5_0", "5_0"),
	array("outdoorsy shovel", "8575", "Yellow", "NA", "Tools", "ToolScoopOutdoor_Remake_6_0", "6_0"),
	array("outdoorsy shovel", "8575", "Black", "NA", "Tools", "ToolScoopOutdoor_Remake_7_0", "7_0"),
	array("outdoorsy slingshot", "8579", "Avocado", "NA", "Tools", "ToolSlingshotOutdoor_Remake_0_0", "0_0"),
	array("outdoorsy slingshot", "8579", "Orange", "NA", "Tools", "ToolSlingshotOutdoor_Remake_1_0", "1_0"),
	array("outdoorsy slingshot", "8579", "Light blue", "NA", "Tools", "ToolSlingshotOutdoor_Remake_2_0", "2_0"),
	array("outdoorsy slingshot", "8579", "Red", "NA", "Tools", "ToolSlingshotOutdoor_Remake_3_0", "3_0"),
	array("outdoorsy slingshot", "8579", "Beige", "NA", "Tools", "ToolSlingshotOutdoor_Remake_4_0", "4_0"),
	array("outdoorsy slingshot", "8579", "Pink", "NA", "Tools", "ToolSlingshotOutdoor_Remake_5_0", "5_0"),
	array("outdoorsy slingshot", "8579", "Yellow", "NA", "Tools", "ToolSlingshotOutdoor_Remake_6_0", "6_0"),
	array("outdoorsy slingshot", "8579", "Black", "NA", "Tools", "ToolSlingshotOutdoor_Remake_7_0", "7_0"),
	array("outdoorsy watering can", "8536", "Avocado", "NA", "Tools", "ToolWateringOutdoor_Remake_0_0", "0_0"),
	array("outdoorsy watering can", "8536", "Orange", "NA", "Tools", "ToolWateringOutdoor_Remake_1_0", "1_0"),
	array("outdoorsy watering can", "8536", "Light blue", "NA", "Tools", "ToolWateringOutdoor_Remake_2_0", "2_0"),
	array("outdoorsy watering can", "8536", "Red", "NA", "Tools", "ToolWateringOutdoor_Remake_3_0", "3_0"),
	array("outdoorsy watering can", "8536", "Beige", "NA", "Tools", "ToolWateringOutdoor_Remake_4_0", "4_0"),
	array("outdoorsy watering can", "8536", "Pink", "NA", "Tools", "ToolWateringOutdoor_Remake_5_0", "5_0"),
	array("outdoorsy watering can", "8536", "Yellow", "NA", "Tools", "ToolWateringOutdoor_Remake_6_0", "6_0"),
	array("outdoorsy watering can", "8536", "Black", "NA", "Tools", "ToolWateringOutdoor_Remake_7_0", "7_0"),
	array("pan flute", "5517", "NA", "NA", "Tools", "ToolPanpipe", "NA"),
	array("pansy wand", "5091", "NA", "NA", "Tools", "ToolStickPansy", "NA"),
	array("party popper", "2753", "NA", "NA", "Tools", "ToolCracker", "NA"),
	array("printed-design shovel", "8576", "Light blue", "NA", "Tools", "ToolScoopPattern_Remake_0_0", "0_0"),
	array("printed-design shovel", "8576", "White", "NA", "Tools", "ToolScoopPattern_Remake_1_0", "1_0"),
	array("printed-design shovel", "8576", "Yellow", "NA", "Tools", "ToolScoopPattern_Remake_2_0", "2_0"),
	array("printed-design shovel", "8576", "Pink", "NA", "Tools", "ToolScoopPattern_Remake_3_0", "3_0"),
	array("printed-design shovel", "8576", "Green", "NA", "Tools", "ToolScoopPattern_Remake_4_0", "4_0"),
	array("printed-design shovel", "8576", "Blue", "NA", "Tools", "ToolScoopPattern_Remake_5_0", "5_0"),
	array("printed-design shovel", "8576", "Purple", "NA", "Tools", "ToolScoopPattern_Remake_6_0", "6_0"),
	array("printed-design shovel", "8576", "Black", "NA", "Tools", "ToolScoopPattern_Remake_7_0", "7_0"),
	array("rose wand", "5093", "NA", "NA", "Tools", "ToolStickRose", "NA"),
	array("shell wand", "7586", "NA", "NA", "Tools", "ToolStickShell", "NA"),
	array("shovel", "2099", "Red", "NA", "Tools", "ToolScoop_Remake_0_0", "0_0"),
	array("shovel", "2099", "Yellow", "NA", "Tools", "ToolScoop_Remake_1_0", "1_0"),
	array("shovel", "2099", "Green", "NA", "Tools", "ToolScoop_Remake_2_0", "2_0"),
	array("shovel", "2099", "Blue", "NA", "Tools", "ToolScoop_Remake_3_0", "3_0"),
	array("shovel", "2099", "Purple", "NA", "Tools", "ToolScoop_Remake_4_0", "4_0"),
	array("shovel", "2099", "Pink", "NA", "Tools", "ToolScoop_Remake_5_0", "5_0"),
	array("shovel", "2099", "White", "NA", "Tools", "ToolScoop_Remake_6_0", "6_0"),
	array("shovel", "2099", "Black", "NA", "Tools", "ToolScoop_Remake_7_0", "7_0"),
	array("slingshot", "2822", "Red", "NA", "Tools", "ToolSlingshot_Remake_0_0", "0_0"),
	array("slingshot", "2822", "Yellow", "NA", "Tools", "ToolSlingshot_Remake_1_0", "1_0"),
	array("slingshot", "2822", "Green", "NA", "Tools", "ToolSlingshot_Remake_2_0", "2_0"),
	array("slingshot", "2822", "Blue", "NA", "Tools", "ToolSlingshot_Remake_3_0", "3_0"),
	array("slingshot", "2822", "Purple", "NA", "Tools", "ToolSlingshot_Remake_4_0", "4_0"),
	array("slingshot", "2822", "Pink", "NA", "Tools", "ToolSlingshot_Remake_5_0", "5_0"),
	array("slingshot", "2822", "White", "NA", "Tools", "ToolSlingshot_Remake_6_0", "6_0"),
	array("slingshot", "2822", "Gray", "NA", "Tools", "ToolSlingshot_Remake_7_0", "7_0"),
	array("star net", "8176", "Yellow", "NA", "Tools", "ToolNetStar_Remake_0_0", "0_0"),
	array("star net", "8176", "Red", "NA", "Tools", "ToolNetStar_Remake_1_0", "1_0"),
	array("star net", "8176", "Blue", "NA", "Tools", "ToolNetStar_Remake_2_0", "2_0"),
	array("star net", "8176", "Light green", "NA", "Tools", "ToolNetStar_Remake_3_0", "3_0"),
	array("star net", "8176", "Pink", "NA", "Tools", "ToolNetStar_Remake_4_0", "4_0"),
	array("star net", "8176", "Purple", "NA", "Tools", "ToolNetStar_Remake_5_0", "5_0"),
	array("star net", "8176", "Light blue", "NA", "Tools", "ToolNetStar_Remake_6_0", "6_0"),
	array("star net", "8176", "Green", "NA", "Tools", "ToolNetStar_Remake_7_0", "7_0"),
	array("star wand", "2544", "NA", "NA", "Tools", "ToolChangeStick", "NA"),
	array("stone axe", "5856", "NA", "NA", "Tools", "ToolAxeStoneNormal", "NA"),
	array("tambourine", "5430", "NA", "NA", "Tools", "ToolTambourine", "NA"),
	array("timer", "3331", "NA", "NA", "Tools", "ToolTimer", "NA"),
	array("tree-branch wand", "7587", "NA", "NA", "Tools", "ToolStickTree", "NA"),
	array("tulip wand", "5085", "NA", "NA", "Tools", "ToolStickTulip", "NA"),
	array("vaulting pole", "4703", "NA", "NA", "Tools", "LongWoodenStick", "NA"),
	array("wand", "7584", "NA", "NA", "Tools", "ToolStickWood", "NA"),
	array("watering can", "2379", "Blue", "NA", "Tools", "ToolWatering_Remake_0_0", "0_0"),
	array("watering can", "2379", "Orange", "NA", "Tools", "ToolWatering_Remake_1_0", "1_0"),
	array("watering can", "2379", "Green", "NA", "Tools", "ToolWatering_Remake_2_0", "2_0"),
	array("watering can", "2379", "Red", "NA", "Tools", "ToolWatering_Remake_3_0", "3_0"),
	array("watering can", "2379", "Purple", "NA", "Tools", "ToolWatering_Remake_4_0", "4_0"),
	array("watering can", "2379", "Pink", "NA", "Tools", "ToolWatering_Remake_5_0", "5_0"),
	array("watering can", "2379", "White", "NA", "Tools", "ToolWatering_Remake_6_0", "6_0"),
	array("watering can", "2379", "Black", "NA", "Tools", "ToolWatering_Remake_7_0", "7_0"),
	array("wedding wand", "12695", "NA", "NA", "Tools", "ToolStickJune", "NA"),
	array("windflower wand", "5084", "NA", "NA", "Tools", "ToolStickAnemones", "NA"),
	array("worn axe", "12615", "NA", "NA", "Tools", "ToolAxeFragile", "NA"),
);

echo("\n");
$index = 0;
foreach ($_fileArray as $array)  {

	$index++;
	$filename = $array[5].".png";
	$targetPath = "./tools/".$filename;

	if (file_exists($targetPath))  {
		echo("File $filename already exists...Skip\n");
		continue;
	}

	echo("Downloading #$index '$filename'...");
	$url = "https://acnhcdn.com/latest/FtrIcon/".$filename;
	$content = file_get_contents($url);
	file_put_contents($targetPath, $content);
	echo("Done\n");
}
echo("\n");
?>